src/objects/Assignment__c.object
<CustomObject>
    <description>Challenge 2287 Object Model</description>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Assignments</relationshipLabel>
        <relationshipName>Assignments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Assignment</label>
    <nameField>
        <displayFormat>ASSIGNMENT-{0000}</displayFormat>
        <label>Assignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Milestone__c.object
<CustomObject>
    <description>Challenge 2287 Object</description>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Milestones</relationshipLabel>
        <relationshipName>Milestones</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Task__c</fullName>
        <label>Task</label>
        <referenceTo>Task__c</referenceTo>
        <relationshipLabel>Milestones</relationshipLabel>
        <relationshipName>Milestones</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Milestone</label>
    <nameField>
        <label>Milestone Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Milestones</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Project__c.object
<CustomObject>
    <description>Challenge 2287 Object</description>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Resource__c.object
<CustomObject>
    <description>Challenge 2287 Object Model</description>
    <fields>
        <fullName>Assignment__c</fullName>
        <label>Assignment</label>
        <referenceTo>Assignment__c</referenceTo>
        <relationshipLabel>Resources</relationshipLabel>
        <relationshipName>Resources</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Standard_Rate__c</fullName>
        <label>Standard Rate</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Unique_ID__c</fullName>
        <inlineHelpText>Unique Resource ID on a Project</inlineHelpText>
        <label>Unique ID</label>
        <precision>16</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Resource</label>
    <nameField>
        <label>Resource Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Resources</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Task__c.object
<CustomObject>
    <description>Challenge 2287 Object</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Milestone__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Milestone</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Tasks</relationshipLabel>
        <relationshipName>Tasks</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Resource__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Resource</label>
        <referenceTo>Resource__c</referenceTo>
        <relationshipLabel>Tasks</relationshipLabel>
        <relationshipName>Tasks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Unique_ID__c</fullName>
        <inlineHelpText>Unique Task ID</inlineHelpText>
        <label>Unique ID</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Task</label>
    <nameField>
        <label>Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/exportProjectController.cls
global with sharing class exportProjectController {
    private Project__c recs;
    private ApexPages.standardController setting_controller;

    public exportProjectController(Apexpages.standardController stdController){
        this.setting_controller = stdController;
        this.recs = (Project__c) this.setting_controller.getRecord();
    }

    @RemoteAction
    global static projectModel.project buildJSON(String projectId){
    	   Project__c projectrec = [select id, name from Project__c where id = :projectId];
        projectModel.Project result = new projectModel.Project();
        result.projectTitle = projectrec.name;
        
        // query the Resource
        List<Resource__c> resourcesrec = [select id, name, standard_rate__c, type__c, unique_id__c
                                            from Resource__c
                                            where assignment__r.project__c = :projectId];
        List<projectModel.resource> newresources = new List<projectModel.resource>();
        for (Resource__c rec : resourcesrec){
        	   projectModel.resource newresource = new projectModel.resource();
        	   newresource.name = rec.name;
        	   newresource.type = rec.type__c;
        	   newresources.add(newresource);
        }
        result.resources = newresources;
        
        List<Task__c> tasksrec = [select id, name, milestone__c, active__c from Task__c where project__c = :projectId];
        List<projectModel.task> newtasks = new List<projectModel.task>();
        for (Task__c rec : tasksrec){
        	   projectModel.task newtask = new projectModel.task();
        	   newtask.name = rec.name;
        	   newtask.milestone = rec.milestone__c;
        	   newtask.active = rec.active__c;
        	   newtasks.add(newtask);
        }
        result.tasks = newtasks;
        return result;
    }

    @isTest
    static void testController(){
        Project__c newproject = new Project__c(name='new project');
        insert(newproject);
    
        Task__c newtask = new Task__c(name='task 1', active__c = true, milestone__c = true, project__c = newproject.id);
        insert(newtask);
        
        Assignment__c newassignment = new Assignment__c(project__c = newproject.id);
        insert(newassignment);
        
        Resource__c newresource = new Resource__c(name='resource-1', assignment__c = newassignment.id);
        insert(newresource);
    
        Apexpages.standardController ast = new Apexpages.standardController(newproject);
        Test.startTest();
        exportProjectController epc = new exportProjectController(ast);

        projectModel.project temp = exportProjectController.buildJSON(newproject.id);
        system.assert(temp != null);
        
        Test.stopTest();
    }
}