src/objects/Assignment__c.object
<CustomObject>
    <description>Challenge 2287 Object Model</description>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Assignments</relationshipLabel>
        <relationshipName>Assignments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Resource_unique_ID__c</fullName>
        <description>Resource unique ID for this assignment -- from MPP</description>
        <label>Resource unique ID</label>
        <precision>16</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Assignment</label>
    <nameField>
        <displayFormat>ASSIGNMENT-{0000}</displayFormat>
        <label>Assignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Milestone__c.object
<CustomObject>
    <description>Challenge 2287 Object</description>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Milestones</relationshipLabel>
        <relationshipName>Milestones</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Task__c</fullName>
        <label>Task</label>
        <referenceTo>Task__c</referenceTo>
        <relationshipLabel>Milestones</relationshipLabel>
        <relationshipName>Milestones</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Milestone</label>
    <nameField>
        <label>Milestone Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Milestones</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Project__c.object
<CustomObject>
    <description>Challenge 2287 Object</description>
    <fields>
        <fullName>Author__c</fullName>
        <label>Author</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Raw_JSON__c</fullName>
        <label>Raw JSON</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Resource__c.object
<CustomObject>
    <description>Challenge 2287 Object Model</description>
    <fields>
        <fullName>Assignment__c</fullName>
        <label>Assignment</label>
        <referenceTo>Assignment__c</referenceTo>
        <relationshipLabel>Resources</relationshipLabel>
        <relationshipName>Resources</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Standard_Rate__c</fullName>
        <label>Standard Rate</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Unique_ID__c</fullName>
        <inlineHelpText>Unique Resource ID on a Project</inlineHelpText>
        <label>Unique ID</label>
        <precision>16</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>id__c</fullName>
        <inlineHelpText>external id of the resources (shows the order of the resource respective to the other resources)</inlineHelpText>
        <label>id</label>
        <precision>15</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Resource</label>
    <nameField>
        <label>Resource Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Resources</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Task__c.object
<CustomObject>
    <description>Challenge 2287 Object</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Milestone__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Milestone</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Percentage_Complete__c</fullName>
        <label>Percentage Complete</label>
        <precision>13</precision>
        <scale>3</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Tasks</relationshipLabel>
        <relationshipName>Tasks</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Resource__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Resource</label>
        <referenceTo>Resource__c</referenceTo>
        <relationshipLabel>Tasks</relationshipLabel>
        <relationshipName>Tasks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Unique_ID__c</fullName>
        <inlineHelpText>Unique Task ID</inlineHelpText>
        <label>Unique ID</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>id__c</fullName>
        <inlineHelpText>Shows the id of task in order they appear correspond to the other Task</inlineHelpText>
        <label>id</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Task</label>
    <nameField>
        <label>Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/importProjectController.cls
/*
 * Controller ImportProject Page
 *
 * Unit Test : Test_Project (83%)
 * @author : Sanny Mulyono <smulyono@me.com -- http://smulyono.github.io/>
 */
global with sharing class importProjectController {
    private ApexPages.StandardSetController setting_controller;

    public importProjectController(ApexPages.StandardSetController controller){
        this.setting_controller = controller;
    }

    @RemoteAction
    global static projectModel.project operateJSON(String rawJSON){
        projectModel.Project result = (projectModel.Project)JSON.deserialize(rawJSON, projectModel.Project.class);
        // do some synchronized result :: 4 DML call
        if (!Schema.SobjectType.Project__c.isCreateable() ||
            !Schema.Sobjecttype.Resource__c.isCreateable() ||
            !Schema.Sobjecttype.Task__c.isCreateable() ||
            !Schema.Sobjecttype.Milestone__c.isCreateable()){
            // just return the JSON without doing any DML call
            return result;
        }
        // Mark the savepoint here, since any failure in DML
        // it will have to rollback everything
        Savepoint sp = Database.setsavepoint();
        // Taking care the project
        Project__c newproject = new Project__c(
            name = result.projectTitle,
            author__c = result.publisher,
            raw_json__c =rawJSON
            );

        try {
            insert(newproject);
        } catch (DMLException ev){
            Database.rollback(sp);
            return result;
        }

        // Deal with Assignments
        // NOTE :: From the requirement, it requested that the assignments
        //      have one to many with project and one-to-one with Resource.
        //      This is different with the Project Schema in MPXJ
        //      (http://mpxj.sourceforge.net/howto-start.html).
        //      Also in microsoft project, we are allowed to assign multiple
        //      resources into one task; which the current requirement are not
        //      supported.
        List<Assignment__c> newassignments = new List<Assignment__c>();
        // Create the map to match task with resources, because of the different
        // project schmea in MPXJ, so for this requirement we only consider
        // one task can be assigned to only maximum one resource
        Map<Integer, Integer> map_taskuniqueid_resourceid = new Map<Integer, Integer>();
        // Create the map to match one assignment to one resource, based on the
        // schema given on the requirement then one resource relate to one assignment
        Map<Decimal, Id> map_resourceuniqueid_assignmentid = new Map<Decimal, Id>();
        for (projectModel.Assignment rec : result.assignments){
            Assignment__c newassignment = new Assignment__c(
                project__c = newproject.id,
                Resource_unique_ID__c = rec.resourceUniqueId
                );
            newassignments.add(newassignment);
            if (rec.taskUniqueId != null && rec.resourceUniqueId != null){
                map_taskuniqueid_resourceid.put(rec.taskUniqueId, rec.resourceUniqueId);
            }
        }
        if (newassignments.size() > 0){
            try {
                insert(newassignments);
                for (Assignment__c record : newassignments){
                    if (record.Resource_unique_ID__c != null){
                        map_resourceuniqueid_assignmentid.put(record.Resource_unique_ID__c, record.id);
                    }
                }
            } catch (DMLException ev){
                Database.rollback(sp);
                return result;
            }
        }

        // Deal with the resources
        List<Resource__c> newresources = new List<Resource__c>();
        for (projectModel.Resource rec : result.resources){
            if (map_resourceuniqueid_assignmentid.containsKey(rec.uniqueId)){
                Id assignmentid = map_resourceuniqueid_assignmentid.get(rec.uniqueId);
                Resource__c newresource = new Resource__c(
                    name = rec.name,
                    type__c = rec.type,
                    id__c = rec.id,
                    Unique_ID__c = rec.uniqueId,
                    Standard_Rate__c = rec.stdRate,
                    Assignment__c = assignmentid
                );
                newresources.add(newresource);
            }
        }

        if (newresources.size() > 0){
            try {
                insert(newresources);
            }catch (DMLException ev){
                Database.rollback(sp);
                return result;
            }
        }

        // Create map to hold the generated ID
        Map<Decimal, Id> mapresource_extid_id = new Map<Decimal, ID>();
        for (Resource__c record : newresources){
            mapresource_extid_id.put(record.Unique_ID__c,record.id);
        }

        // Deal with Tasks
        List<Task__c> newtasks = new List<Task__c>();
        // also deal with milestones
        // Assumptions :: put all task which is part of milestones into
        //                this custom object. There are no further description
        //                in the requirement.
        Boolean milestone_exists = false;
        for (projectModel.Task record : result.tasks){
            Task__c newtask = new Task__c(
                name = record.name,
                active__c = record.active,
                id__c = record.id,
                milestone__c = record.milestone,
                percentage_complete__c = record.percentageComplete,
                project__c = newproject.id,
                unique_id__c = record.uniqueId
                );
            if (map_taskuniqueid_resourceid.containsKey(record.uniqueId)){
                Integer resourceuniqueid = map_taskuniqueid_resourceid.get(record.uniqueId);
                if (mapresource_extid_id.containsKey(resourceUniqueId)){
                    newtask.resource__c = mapresource_extid_id.get(resourceUniqueId);
                }
            }
            newtasks.add(newtask);
            if (record.milestone != null && record.milestone){
                milestone_exists = true;
            }
        }

        // Do the Milestone and Task
        if (newtasks.size() > 0){
            try {
                insert(newtasks);
            } catch (DMLException ev){
                Database.rollback(sp);
                return result;
            }
            List<Milestone__c> newmilestones = new List<Milestone__c>();
            if (milestone_exists){
                for (Task__c record : newtasks){
                    if (record.milestone__c){
                        Milestone__c newmilestone = new Milestone__c(
                            name = record.name,
                            task__c = record.id,
                            project__c = newproject.id
                            );
                        newmilestones.add(newmilestone);
                    }
                }
            }
            if (newmilestones.size() > 0){
                try {
                    insert(newmilestones);
                } catch(DMLException ev){
                    Database.rollback(sp);
                    return result;
                }
            }
        }

        // Mark the complete process by passing the generated Project ID
        result.generatedId = newproject.id;
        return result;
    }

}